/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: S4pM/2E3xe6ikxalNWCPQbWqI+5LrddwhsoMUSzKpfC1l95XAqqqRUqHAEFRRnLKyZkkLSXZDcwLLPtuRtPwUQ==
 */

/* eslint-disable */
// tslint:disable

import Instance from './instance'
import User from './user'

interface Blockfile {
  content: string
  entry_limit: number
  i: number & {readonly __brand?: 'blockfile_i'}
  i_instance: Instance['i']
  i_user: User['i']
}
export default Blockfile;

interface Blockfile_InsertParameters {
  content: string
  entry_limit: number
  i: number & {readonly __brand?: 'blockfile_i'}
  i_instance: Instance['i']
  i_user: User['i']
}
export type {Blockfile_InsertParameters}
