/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: x6Zna+T5j6FPolT538aKrnBjfsT5j+NkDfPkOGOsWGGCNtMZE8Cztd6fXrXmpoRyy+K8OwxiXDnJGyRgX2fMaQ==
 */

/* eslint-disable */
// tslint:disable

import Instance from './instance'
import User from './user'

interface Blocklist {
  address: string
  entry_limit: number
  /**
   * @default nextval('blocklist_i_seq'::regclass)
   */
  i: number & {readonly __brand?: 'blocklist_i'}
  /**
   * @default nextval('blocklist_i_instance_seq'::regclass)
   */
  i_instance: Instance['i']
  /**
   * @default nextval('blocklist_i_user_seq'::regclass)
   */
  i_user: User['i']
}
export default Blocklist;

interface Blocklist_InsertParameters {
  address: string
  entry_limit: number
  /**
   * @default nextval('blocklist_i_seq'::regclass)
   */
  i?: number & {readonly __brand?: 'blocklist_i'}
  /**
   * @default nextval('blocklist_i_instance_seq'::regclass)
   */
  i_instance?: Instance['i']
  /**
   * @default nextval('blocklist_i_user_seq'::regclass)
   */
  i_user?: User['i']
}
export type {Blocklist_InsertParameters}
