/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ECIMPJa9GepiyH/bwe6e9DQd+qB5oQdYUuYX5iPsOmI/P6Z+yV7IRgVSIs1hw132yHnVj3nGz0wzvqdgdHwCWQ==
 */

/* eslint-disable */
// tslint:disable

import User from './user'

interface Instance {
  alias: string
  created_at: Date
  filter_limit: number
  /**
   * @default nextval('instance_i_seq'::regclass)
   */
  i: number & {readonly __brand?: 'instance_i'}
  /**
   * @default nextval('instance_i_user_seq'::regclass)
   */
  i_user: User['i']
  query_limit: number
  status: number
  updated_at: Date
  upstream: string
}
export default Instance;

interface Instance_InsertParameters {
  alias: string
  created_at: Date
  filter_limit: number
  /**
   * @default nextval('instance_i_seq'::regclass)
   */
  i?: number & {readonly __brand?: 'instance_i'}
  /**
   * @default nextval('instance_i_user_seq'::regclass)
   */
  i_user?: User['i']
  query_limit: number
  status: number
  updated_at: Date
  upstream: string
}
export type {Instance_InsertParameters}
