/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: pZ5ksAbwUGKEB6QK5ekTgRvAk+/mWg5CkSFnXYBtpmHEdX8iYL9nwl3zIhJAjN6qsKlxTKvCyDrrioYFcJqGAg==
 */

/* eslint-disable */
// tslint:disable

import User from './user'

interface Instance {
  alias: string
  filter_limit: number
  /**
   * @default nextval('instance_i_seq'::regclass)
   */
  i: number & {readonly __brand?: 'instance_i'}
  /**
   * @default nextval('instance_i_user_seq'::regclass)
   */
  i_user: User['i']
  query_limit: number
  upstream: string
}
export default Instance;

interface Instance_InsertParameters {
  alias: string
  filter_limit: number
  /**
   * @default nextval('instance_i_seq'::regclass)
   */
  i?: number & {readonly __brand?: 'instance_i'}
  /**
   * @default nextval('instance_i_user_seq'::regclass)
   */
  i_user?: User['i']
  query_limit: number
  upstream: string
}
export type {Instance_InsertParameters}
