/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8MnWPhhYFStjzo7rBCJiT1uuO3EH+/t63I6nnXYRdd+Ifp96rc/aCObM5ESzO07HKwX4nD1s4DEElrY4GtwP7Q==
 */

/* eslint-disable */
// tslint:disable

import User from './user'

interface Instance {
  alias: string
  /**
   * @default nextval('instance_i_seq'::regclass)
   */
  i: number & {readonly __brand?: 'instance_i'}
  /**
   * @default nextval('instance_i_user_seq'::regclass)
   */
  i_user: User['i']
  manual_limit: number
  query_limit: number
  upstream: string
}
export default Instance;

interface Instance_InsertParameters {
  alias: string
  /**
   * @default nextval('instance_i_seq'::regclass)
   */
  i?: number & {readonly __brand?: 'instance_i'}
  /**
   * @default nextval('instance_i_user_seq'::regclass)
   */
  i_user?: User['i']
  manual_limit: number
  query_limit: number
  upstream: string
}
export type {Instance_InsertParameters}
