/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZIlARLJHU9nS5xDJ/VH66dGsRLKNf1UTMlL4K5WoAlg4t0f7/ioJTUCmjnmzT+EYOMcT5E6W6QI59l8PxmEQkA==
 */

/* eslint-disable */
// tslint:disable

import User from './user'

interface Session {
  created_at: Date
  /**
   * @default nextval('session_i_seq'::regclass)
   */
  i: number & {readonly __brand?: 'session_i'}
  /**
   * @default nextval('session_i_user_seq'::regclass)
   */
  i_user: User['i']
  name: string
  token: string
}
export default Session;

interface Session_InsertParameters {
  created_at: Date
  /**
   * @default nextval('session_i_seq'::regclass)
   */
  i?: number & {readonly __brand?: 'session_i'}
  /**
   * @default nextval('session_i_user_seq'::regclass)
   */
  i_user?: User['i']
  name: string
  token: string
}
export type {Session_InsertParameters}
