/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1dIOSNUgD5WhojBjCqBP9Hqbb9mZqF8Rm0Y+rVf3/J4DYq1FCd6IrcpdQ/2zrSUEzGiBSpLpe9qvX0ctr7nBUQ==
 */

/* eslint-disable */
// tslint:disable

interface User {
  created_at: Date
  email: string
  email_token: number
  /**
   * @default nextval('user_i_seq'::regclass)
   */
  i: number & {readonly __brand?: 'user_i'}
  password: string
}
export default User;

interface User_InsertParameters {
  created_at: Date
  email: string
  email_token: number
  /**
   * @default nextval('user_i_seq'::regclass)
   */
  i?: number & {readonly __brand?: 'user_i'}
  password: string
}
export type {User_InsertParameters}
