/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: MLGdsNstgB+sXokKYllQhC/nO2IdU+zaEarQLdaGYkGGODUjkJr6jiqQFcDwey0rrcbw34cHOIiu+sJSHdTUqg==
 */

/* eslint-disable */
// tslint:disable

interface User {
  created_at: Date
  email: string
  email_token: number
  i: number & {readonly __brand?: 'user_i'}
  instance_limit: number
  password: string
}
export default User;

interface User_InsertParameters {
  created_at: Date
  email: string
  email_token: number
  i: number & {readonly __brand?: 'user_i'}
  instance_limit: number
  password: string
}
export type {User_InsertParameters}
